/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
// @ts-nocheck - react-three doesn't support typescript
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/glassVision.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        scale={[6, 1.5, 0.25]}
      />
    </group>
  );
}

useGLTF.preload("/glassVision.glb");
